#ifndef WW_TEST_SERIALIZERTESTDEFINED
#define WW_TEST_SERIALIZERTESTDEFINED

#define WW_TEST_JSONSERIALIZER_PROTOCOL_COLLECTION_KEY R"("ArticleCollection":)"
#define WW_TEST_JSONSERIALIZER_PROTOCOL_HEADER_1 R"("program":"wikiwalker")"
#define WW_TEST_JSONSERIALIZER_PROTOCOL_HEADER_2 R"("scheme-version":2)"

#endif WW_TEST_SERIALIZERTESTDEFINED